version: "3.9"
   
services:
    db:
        build: ./docker/mysql
        image: "mysql:${PROJECT_NAME}"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./db_data/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=django
            - MYSQL_USER=djangouser
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        cap_add:
            - SYS_NICE
    nginx:
        build: ./docker/nginx
        image: "nginx:${PROJECT_NAME}"
        ports:
        - "127.0.0.1:${NGINX_PORT}:80"
        depends_on:
        - django
        volumes:
        - ./docker/nginx/config:/etc/nginx/conf.d:ro
        - ./static:/static
        - ./media:/media
    django:
        build: .
        image: "python:${PROJECT_NAME}"
        command: bash -c "
            sleep 5 && 
            python manage.py makemigrations && 
            python manage.py migrate && 
            python manage.py collectstatic --noinput && 
            gunicorn --bind :8000 ${PROJECT_NAME}.wsgi"
        volumes:
            - ".:/${PROJECT_NAME}"
        depends_on:
            - db